<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Digital Clock with Time Zones</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      text-align: center;
      padding: 50px;
      background-color: #f4f4f9;
    }
    h1 {
      font-size: 2em;
      margin-bottom: 20px;
    }
    .clock {
      font-size: 1.5em;
      margin: 20px 0;
      padding: 15px;
      border: 1px solid #ccc;
      display: inline-block;
      background-color: #fff;
      border-radius: 8px;
      box-shadow: 2px 2px 6px rgba(0, 0, 0, 0.1);
    }
    .timezone {
      font-weight: bold;
      margin-bottom: 10px;
    }
  </style>
</head>
<body>
  <h1>Digital Clock with Time Zones</h1>

  <div id="clocks"></div>

  <script>
    // Time zones to display
    const timeZones = [
      { name: "UTC", timeZone: "UTC" },
      { name: "New York (EST)", timeZone: "America/New_York" },
      { name: "London (GMT)", timeZone: "Europe/London" },
      { name: "Tokyo (JST)", timeZone: "Asia/Tokyo" },
      { name: "Sydney (AEDT)", timeZone: "Australia/Sydney" }
    ];

    const clocksContainer = document.getElementById('clocks');

    // Function to create a clock for each time zone
    function createClocks() {
      timeZones.forEach(zone => {
        const clockDiv = document.createElement('div');
        clockDiv.className = 'clock';
        clockDiv.id = `clock-${zone.name}`;
        clockDiv.innerHTML = `
          <div class="timezone">${zone.name}</div>
          <div class="time" id="time-${zone.name}">00:00:00</div>
        `;
        clocksContainer.appendChild(clockDiv);
      });
    }

    // Function to update the time for each time zone
    function updateClocks() {
      timeZones.forEach(zone => {
        const timeDiv = document.getElementById(`time-${zone.name}`);
        const now = new Date();
        const options = {
          timeZone: zone.timeZone,
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit',
          hour12: false
        };
        const timeString = now.toLocaleTimeString('en-US', options);
        timeDiv.textContent = timeString;
      });
    }

    // Initialize clocks on page load
    createClocks();

    // Update clocks every second
    setInterval(updateClocks, 1000);
  </script>
</body>
</html>
